
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION_DECLARATION_START = 13;
  public static final int STRING_LITERAL = 10;
  public static final int PREFIX = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ELSE = 6;
  public static final int COMMA = 9;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int IDENTIFIER = 11;
  public static final int IF_START = 5;
  public static final int SUFFIX = 7;
  public static final int FUNCTION_START = 12;
  public static final int RBRACE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "RPAREN",
  "RBRACE",
  "IF_START",
  "ELSE",
  "SUFFIX",
  "PREFIX",
  "COMMA",
  "STRING_LITERAL",
  "IDENTIFIER",
  "FUNCTION_START",
  "FUNCTION_DECLARATION_START"
  };
}

